# Generated by Django 4.0.1 on 2022-02-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0004_order_orderproduct_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
    ]
