# Generated by Django 4.0.1 on 2022-02-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0007_alter_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
